### ISSUE TITLE
Extend Binance COIN-Margined Futures API support

### ISSUE THREAD

**Issue by dmitrii-doronin** [bhftbootcamp/CryptoAPIs.jl#1]
### Description
The Binance API provides a comprehensive set of functionalities for interacting with the Binance platform. However, there are some methods that are currently not implemented in our application. This issue aims to address this gap.

### Basic requirements
- [ ] The methods must confirm to the library's existing structure and guidelines
- [ ] The methods must be tested and cover all the response cases
- [ ] The methods must be documented 

### Tasks
- [ ]  [GET dapi/v1/fundingRate](https://binance-docs.github.io/apidocs/delivery/en/#get-funding-rate-history-of-perpetual-futures) 
- [ ] [GET dapi/v1/ticker/24hr](https://binance-docs.github.io/apidocs/delivery/en/#24hr-ticker-price-change-statistics) 
- [ ] [GET dapi/v1/premiumIndex](https://binance-docs.github.io/apidocs/delivery/en/#index-price-and-mark-price)
- [ ] [GET dapi/v1/continuousKlines](https://binance-docs.github.io/apidocs/delivery/en/#continuous-contract-kline-candlestick-data)
