### ISSUE TITLE
Extend Gateio Futures API support

### ISSUE THREAD

**Issue by dmitrii-doronin** [bhftbootcamp/CryptoAPIs.jl#19]
### Description

The Gateio API provides a comprehensive set of functionalities for interacting with the Gateio platform. However, there are some methods that are currently not implemented in our application. This issue aims to address this gap.

### Basic requirements

- [ ] The methods must confirm to the library's existing structure
- [ ] The methods must be tested and cover all the API response cases
- [ ] The methods must be documented in accordance with guidelines

### Tasks

- [ ] [GET /futures/{settle}/contracts](https://www.gate.io/docs/developers/apiv4/en/#list-all-futures-contracts)
- [ ] [GET /futures/{settle}/order_book](https://www.gate.io/docs/developers/apiv4/en/#futures-order-book)
- [ ] [GET /futures/{settle}/tickers](https://www.gate.io/docs/developers/apiv4/en/#list-futures-tickers)
- [ ] [GET /futures/{settle}/funding_rate](https://www.gate.io/docs/developers/apiv4/en/#funding-rate-history)
- [ ] [GET /futures/{settle}/candlesticks](https://www.gate.io/docs/developers/apiv4/en/#get-futures-candlesticks) implement only mark_klines method
