### ISSUE TITLE
Extend Binance Spot API support

### ISSUE THREAD

**Issue by dmitrii-doronin** [bhftbootcamp/CryptoAPIs.jl#2]
### Description
The Binance API provides a comprehensive set of functionalities for interacting with the Binance platform. However, there are some methods that are currently not implemented in our application. This issue aims to address this gap.

### Basic requirements
- [ ] The methods must confirm to the library's existing structure and guidelines
- [ ] The methods must be tested and cover all the response cases
- [ ] The methods must be documented 

### Tasks
- [ ]  [GET api/v3/exchangeInfo](https://binance-docs.github.io/apidocs/spot/en/#exchange-information)
