### ISSUE TITLE
Extend Binance USD-Margined Futures API support

### ISSUE THREAD

**Issue by dmitrii-doronin** [bhftbootcamp/CryptoAPIs.jl#3]
### Description
The Binance API provides a comprehensive set of functionalities for interacting with the Binance platform. However, there are some methods that are currently not implemented in our application. This issue aims to address this gap.

### Basic requirements
- [ ] The methods must confirm to the library's existing structure and guidelines
- [ ] The methods must be tested and cover all the response cases
- [ ] The methods must be documented 

### Tasks
- [ ]  [GET fapi/v1/continuousKlines](https://binance-docs.github.io/apidocs/futures/en/#continuous-contract-kline-candlestick-data)
- [ ]  [GET futures/data/globalLongShortAccountRatio](https://binance-docs.github.io/apidocs/futures/en/#long-short-ratio)
- [ ] [GET futures/data/openInterestHist](https://binance-docs.github.io/apidocs/futures/en/#open-interest-statistics)
- [ ] [GET fapi/v1/premiumIndex](https://binance-docs.github.io/apidocs/futures/en/#mark-price)
- [ ] [GET futures/data/takerlongshortRatio](https://binance-docs.github.io/apidocs/futures/en/#taker-buy-sell-volume)
- [ ] [GET futures/data/topLongShortAccountRatio](https://binance-docs.github.io/apidocs/futures/en/#top-trader-long-short-ratio-accounts)
- [ ] [GET futures/data/topLongShortPositionRatio](https://binance-docs.github.io/apidocs/futures/en/#top-trader-long-short-ratio-positions)
