### ISSUE TITLE
Extend Coinbase Spot API support

### ISSUE THREAD

**Issue by dmitrii-doronin** [bhftbootcamp/CryptoAPIs.jl#4]
### Description
The Coinbase API provides a comprehensive set of functionalities for interacting with the Coinbase platform. However, there are some methods that are currently not implemented in our application. This issue aims to address this gap.

### Basic requirements
- [ ] The methods must confirm to the library's existing structure
- [ ] The methods must be tested and cover all the API response cases
- [ ] The methods must be documented in accordance with guidelines

### Tasks
- [ ] [GET withdrawals/fee-estimate](https://docs.cloud.coinbase.com/exchange/reference/exchangerestapi_getwithdrawfeeestimate)
- [ ] [GET products/{product_id}/stats](https://docs.cloud.coinbase.com/exchange/reference/exchangerestapi_getproductstats)
