### ISSUE TITLE
Implement initial Crypto.com support

### ISSUE THREAD

**Issue by dmitrii-doronin** [bhftbootcamp/CryptoAPIs.jl#5]
### Description
Crypto.com is a popular platform for trading and managing cryptocurrencies. However, our application currently lacks support for this platform. This task aims to implement initial support for Crypto.com in our application.

### Basic requirements
- [ ] The exchange's structure must be able to accomadate new API methods
- [ ] The methods must confirm to the library's existing structure
- [ ] The methods must be tested and cover all the API response cases
- [ ] The methods must be documented in accordance with guidelines

### Tasks
- [ ] Method for Candles for different currency pairs with different granularity
- [ ] Method for Tickers for different currency pairs with different granularity
- [ ] Method/methods for active trading pairs/markets
- [ ] ~~Method for getting trades/orders history~~
